VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

###########
### kis ###
###########
  config.vm.define "kis" do |config|
    config.vm.box = "generic/fedora30"

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 256
      v.cpus = 1
    end

    config.vm.network "private_network", virtualbox__intnet: "vboxnet1", auto_config: false
    config.vm.network "private_network", virtualbox__intnet: "vboxnet2", auto_config: false

    config.vm.provision "shell", path: "scripts/base.sh", privileged: true
    config.vm.provision "shell", path: "scripts/kis/configure.sh", privileged: true
    config.vm.provision "shell", path: "scripts/kis/install-httpd.sh", privileged: true

    config.vm.hostname = "kis.vagrant"
  end

##############
### amazon ###
##############
  config.vm.define "amazon" do |config|
    config.vm.box = "generic/fedora30"

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 256
      v.cpus = 1
    end

    config.vm.network "private_network", ip: "10.10.10.100", virtualbox__intnet: "vboxnet1"

    config.vm.provision "shell", path: "scripts/base.sh", privileged: true
    config.vm.provision "shell", path: "scripts/amazon/configure.sh", privileged: true

    config.vm.hostname = "amazon.vagrant"
  end

#################
### microsoft ###
#################
  config.vm.define "microsoft" do |config|
    config.vm.box = "generic/fedora30"

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 256
      v.cpus = 1
    end

    config.vm.network "private_network", ip: "10.10.10.200", virtualbox__intnet: "vboxnet2"

    config.vm.provision "shell", path: "scripts/base.sh", privileged: true
    config.vm.provision "shell", path: "scripts/microsoft/configure.sh", privileged: true

    config.vm.hostname = "microsoft.vagrant"
  end

end
