VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#############
### netns ###
#############
  config.vm.define "netns" do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 256
      v.cpus = 1
    end

    config.vm.provision "shell", path: "scripts/base.sh", privileged: true
    config.vm.provision "shell", path: "scripts/configure.sh", privileged: true

    config.vm.hostname = "netns.vagrant"
  end
end
