VAGRANTFILE_API_VERSION = "2"

password = ARGV[0]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
##############
### docker ###
##############
  config.vm.define "docker" do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
    end

    config.vm.network "private_network", ip: "10.0.0.125"

    config.vm.hostname = "docker.vagrant"

    config.vm.provision "shell", path: "scripts/base.sh", privileged: true
    config.vm.provision "shell", path: "scripts/install-docker.sh", privileged: true

    config.vm.synced_folder "files/", "/home/vagrant/docker"
  end

end
